=encoding utf8

=head1 NAME

Ado::Manual - Developers' manual

=head1 DESCRIPTION

L<Ado> is a light on dependencies framework and application for web-projects,
based on L<Mojolicious>, written in the L<Perl programming
language|http://www.perl.org/>. Ado is a typical well structured,
L<MVC|http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller>
L<Mojolicious> application. It aims to allow teams to build on it a CMS, ERP,
CRM or all of them integrated together.

Please note that the project is still a work-in-progress. Parts of it work,
others are simply missing.

=head1 GETTING STARTED

=over

=item * Start a personal blog with L<Ado::Manual::FiveMinutes> if you are impatient.

=item * Read the L<Ado::Manual::Intro> for a general overview.

=item * To see different installation methods, go to
L<Ado::Manual::Installation>.

=item * To learn about plugins and how to write your own plugin, see L<Ado::Manual::Plugins>.

=back

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation with the perldoc command.

	perldoc Ado
	perldoc Ado::Manual #this page

For better experience run the B<C<ado>> application and read the
documentation from your browser.

	/path/to/yourAdo/bin/ado daemon

If you installed C<ado> in your Perl distro, you can simply type:

	ado daemon

Go to http:/localhost:3000/perldoc

You can report bugs and suggest features at
L<http://github.com/kberov/Ado/issues>. Bugs will be considered and fixed as
time permits. Feel invited to make pull requests for your contributions.

If you are simply looking for help with using Ado, please ask your questions
at L<https://groups.google.com/d/forum/ado-dev>.

=head1 CONTRIBUTING

Anybody can contribute by reporting issues via github or fixing typos in the
documentation. To be able to contribute with code, some rules need to be kept.
This is mandatory for any community project. Generally the rules outlined in
L<Mojolicious::Guides::Contributing> apply for L<Ado> too. For specific to Ado
rules see L<Ado::Manual::Contributing>.

We expect that you know how Internet works, how to write Perl modules and are
familiar with L<Mojolicious>.

To ease discussions on Ado further development, a forum was created.
L<https://groups.google.com/d/forum/ado-dev>.

=head1 REST API

Ado strives for strict separation of concerns. The best way to achieve this
is to fully separate the client code from the server code. Ado is ideally
suited for the purpose thanks to L<Mojolicious>. Every resource(route) is
accessible via a browser as C</path/to/resourse> an returns HTML or using
C</path/to/resourse.json> and returns JSON. We follow closely and elaborate
on the recommendations in "RESTful Service Best Practices" at
L<http://www.RestApiTutorial.com>. See L<Ado::Manual::RESTAPI>.

=head1 PLUGINS

Business-specific applications for an Ado-based system are usually implemented
as plugins. One way to contribute to L<Ado> is by writing plugins.

Ado plugins work the same way as L<Mojolicious::Plugins> and share the same
common base trough L<Ado::Plugin> which ISA L<Mojolicious::Plugins>. Ado
plugins have one small additional feature. They can load their own
configuration from C<$ENV{MOJO_HOME}/etc/plugins/plugin_name.conf>.

See L<Ado::Manual::Plugins> and L<Ado::Plugin> for more information.

=head1 CONTINUOUS INTEGRATION

We would like to know that our software is always in good health. We count
on friendly developers and organizations to install and test it
continuously.

L<CPAN Testers Reports for
Ado|http://www.cpantesters.org/distro/A/Ado.html>

L<Travis-CI|https://travis-ci.org/kberov/Ado> 

=for HTML <a href="https://travis-ci.org/kberov/Ado"><img
src="https://travis-ci.org/kberov/Ado.svg?branch=master"></a><br /><br />

=head1 SEE ALSO

L<Ado>, L<Mojolicious::Guides>, L<Mojolicious::Guides::Contributing>,
L<http://www.thefreedictionary.com/ado>.

=head1 AUTHORS

Authors, ordered by contributions
(L<https://github.com/kberov/Ado/graphs/contributors>).

Красимир Беров (Krasimir Berov)(berov@cpan.org)

Вълчо Неделчев (Valcho Nedelchev)(kumcho@vulcho.com)

Joachim Astel

Renee Baecker (module@renee-baecker.de)

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2015 Красимир Беров (Krasimir Berov).

This program is free software, you can redistribute it and/or modify it under
the terms of the GNU Lesser General Public License v3 (LGPL-3.0). You may copy,
distribute and modify the software provided that modifications are open source.
However, software that includes the license may release under a different
license.

See http://opensource.org/licenses/lgpl-3.0.html for more information.
