=encoding utf8

=head1 NAME

Ado::Manual - Getting started with Ado 

=head1 SYNOPSIS

  ado daemon
  Server available at http://127.0.0.1:3000

=head1 DESCRIPTION

L<Ado> is a framework for web projects based on L<Mojolicious>,
written in the L<Perl programming language|http://www.perl.org/>.

Ado is a typical well structured,
L<MVC|http://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller>
L<Mojolicious> application.
It comes with default configuration and a model layer, plugged in by
L<Mojolicious::Plugin::DSC>. An SQLite database is bundled in the distribution 
at C<etc/ado.sqlite> to get started quickly.

Ado provides additional L<plugins|Ado::Plugin> and L<commands|Ado::Command>, 
which promote L<RAD|http://en.wikipedia.org/wiki/Rapid_application_development>,
good practices, and team-work when starting new projects.
The default Ado page uses L<Semantic UI|http://beta.semantic-ui.com/>
via L<Mojolicious::Plugin::SemanticUI> and is a good place to get acquainted.

=head1 INSTALLATION

We strongly recommend using Ado with your own Perl (not the system-wide)!

Ado can be I<installed into any folder of your choice>.
By default it goes into the C<siteprefix> folder of your
B<I<non-system Perl distro>>. When installing Ado in its own folder,
you may want to add the C</path/to/yourAdo/bin> to your C<$PATH>
environment variable. When using Ado as a module from C</path/to/yourAdo/lib>,
add the path to C<$PERL5LIB>.

To install manually Ado after downloading, run the following commands:

  tar -zxf Ado-X.XX.tar.gz
  cd Ado-X.XX/
  perl Build.PL --install_base $HOME/opt/ado
  ./Build installdeps
  ./Build
  ./Build test
  ./Build install

To see more installation methods and details, go to L<Ado::Manual::Installation>.

=head1 SUPPORT AND DOCUMENTATION

After installing, you can find documentation with the
perldoc command.

    perldoc Ado
    perldoc Ado::Manual #this page

For better experience run the B<C<ado>> application and read the documentation
from your browser.

  /path/to/yourAdo/bin/ado daemon

If you installed C<ado> in your Perl distro, you can simply type:

  ado daemon

Go to http:/localhost:3000/perldoc

You can report bugs and suggest features at L<http://github.com/kberov/Ado/issues>.
Bugs will be considered and fixed as time permits.
Feel invited to make pull requests for your contributions.

=head1 CONTRIBUTING

Anybody can contribute by reporting issues via github 
or fixing typos in the documentation.
To be able to contribute with code, some rules need to be kept.
This is mandatory for any community project.
Generally the rules outlined in L<Mojolicious::Guides::Contributing>
apply for L<Ado> too.
For specific to Ado rules see L<Ado::Manual::Contributing>.

We expect that you know how Internet works, how to write Perl modules and 
are familiar with L<Mojolicious>.

=head1 REST API

Ado strives for strict separation of concerns. The best way to achieve 
this is to fully separate the client code from the server code. 
Ado is ideally suited for the purpose thanks to
L<Mojolicious>. Every resource is accessible via the REST API.
We follow closely and elaborate on the recommendations in
"RESTful Service Best Practices" 
at L<www.RestApiTutorial.com>. See L<Ado::Manual::RESTAPI>.

=head1 PLUGINS

Ado plugins work the same way as L<Mojolicious::Plugins> and share 
the same common base trough L<Ado::Plugin>.
Ado plugins have one small additional feature. 
They can load their own configuration from
C<$ENV{MOJO_HOME}/etc/plugins/plugin_name.conf>.
Business-specific applications for an Ado-based system are usually implemented 
as plugins. One way to contribute to L<Ado> is by writing plugins.

See L<Ado::Manual::Plugins> and L<Ado::Plugin> for more information.

=head1 CONTINUOUS INTEGRATION

We would like to know that our software is always in good health so we count on
friendly developers and organizations to install and test it continuously.

L<CPAN Testers Reports for Ado|http://www.cpantesters.org/distro/A/Ado.html>

L<Travis-CI|https://travis-ci.org/kberov/Ado> 


=for HTML <a href="https://travis-ci.org/kberov/Ado"><img src="https://travis-ci.org/kberov/Ado.svg?branch=master"></a><br /><br />


=head1 SEE ALSO

L<Ado>, L<Mojolicious::Guides>, 
L<Mojolicious::Guides::Contributing>,
L<Module::Build::Cookbook/prefix_vs_install_base>, 
L<http://www.thefreedictionary.com/ado>.

=head1 AUTHORS

Authors in order of appearance.

Красимир Беров (Krasimir Berov)(berov@cpan.org) 

Вълчо Неделчев (Valcho Nedelchev)(kumcho@vulcho.com)

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2014 Красимир Беров (Krasimir Berov).

This program is free software, you can redistribute it and/or
modify it under the terms of the 
GNU Lesser General Public License v3 (LGPL-3.0).
You may copy, distribute and modify the software provided that 
modifications are open source. However, software that includes 
the license may release under a different license.

See http://opensource.org/licenses/lgpl-3.0.html for more information.

