=encoding utf8

=head1 NAME

Ado::Manual::FiveMinutes - Start a personal blog in five minutes.

=head1 FIVE MINUTES

Create a directory for L<Ado> and install it in it.

  mkdir ~/ado 
  curl -L https://cpanmin.us | perl - -M https://cpan.metacpan.org -l ~/ado -n Ado

Check if it is running

  ~/ado/bin/ado daemon

You should see: 

  Server available at http://127.0.0.1:3000

Choose a folder under C<public/> to keep your articles written in markdown
and generated as static html files. Let it be C<public/articles>.

  mkdir -p ~/ado/public/articles


Create a template for listing and displaying your articles and save it in
C<site_templates>.

  mkdir site_templates

  %#site_templates/article.html.ep
  % state $articles_folder = app->home->rel_dir('public/articles')


=head1 SEE ALSO

L<Ado::Manual>, L<Ado>, L<Mojolicious::Guides>, 
L<Module::Build::Cookbook/prefix_vs_install_base>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2015 Красимир Беров (Krasimir Berov).

This program is free software, you can redistribute it and/or
modify it under the terms of the 
GNU Lesser General Public License v3 (LGPL-3.0).
