=encoding utf8

=head1 NAME

Ado::Manual::FiveMinutes - Start a personal blog in five minutes.



=head1 SEE ALSO

L<Ado::Manual>, L<Ado>, L<Mojolicious::Guides>, 
L<Module::Build::Cookbook/prefix_vs_install_base>

=head1 COPYRIGHT AND LICENSE

Copyright 2013-2015 Красимир Беров (Krasimir Berov).

This program is free software, you can redistribute it and/or
modify it under the terms of the 
GNU Lesser General Public License v3 (LGPL-3.0).
