=pod

=encoding utf8

=head1 NAME

Ado::Manual::Plugins - Ado plugins and how to write an Ado::Plugin

=head1 DESCRIPTION

There is I<almost> nothing special about writing an L<Ado::Plugin>.


=head1 SYNOPSIS

TODO:...

=head1 PLUGINS

Ado comes with the following default plugins.

=over 2

=item L<Ado::Plugin::Routes>

Keep routes separately.

=back

=head1 SPONSORS

The original author

=head1 SEE ALSO

L<Mojolicious::Plugins>, L<Mojolicious::Plugin>, 


=head1 AUTHOR

Красимир Беров (Krasimir Berov)

=head1 COPYRIGHT AND LICENSE

Copyright 2013 Красимир Беров (Krasimir Berov).

This program is free software, you can redistribute it and/or
modify it under the terms of the 
GNU Lesser General Public License v3 (LGPL-3.0).
You may copy, distribute and modify the software provided that 
modifications are open source. However, software that includes 
the license may release under a different license.

See http://opensource.org/licenses/lgpl-3.0.html for more information.

=cut

